### ISSUE TITLE
Namespace generation for simple projects

### ISSUE THREAD

**Issue by alanpearce** [pomm-project/Cli#11]
The readme states that generated classes are saved under `DatabaseConfigName\SchemaSchema`.
This is a fine default as it works well for both a multi-database & schemata config and a simple single database and schema using PSR-0, but doesn't work for those of us using PSR-4 for our application namespace and wanting to have our entities generated in the same namespace.

I get that using the `DatabaseConfigName\SchemaSchema` layout makes sense for multiple schemata and multiple database configurations, but I think it would be nice for a simple application to have generated files in a simpler structure with:
```
$ ./bin/pomm.php pomm:generate:schema-all --prefix-dir sources/lib --prefix-ns Model pomm_test
 ✓  Creating file 'sources/lib/Model/AutoStructure/Pika.php'.
…
```
Where the `Pika` class is in the `DatabaseConfigName\Model\AutoStructure` namespace (or not? It's just an extra bit to add to `--prefix-ns`).

Is this remotely feasible and does it make sense? I thought I'd check before diving in to the code.

**Comment by chanmix51** [comment]
Imho there should be an option «ns-format» with default `%database%/%schema%Schema` that is used to set classes namespace.

**Comment by sanpii** [comment]
I suggest a ``--psr4`` option. Without, the destination directory is ``%prefix_dir%/%prefix_ns%/%database%/%schema%Schema``. Enable this option makes destination directory egal to ``%prefix_dir%/%database%/%schema%Schema``.

    $ ./bin/pomm.php pomm:generate:schema-all --prefix-dir sources/lib --prefix-ns PommProject\ModelManager\Model pomm_test
     ✓  Creating file 'sources/lib/PommProject/ModelManager/Model/PommTest/PommTestSchema/AutoStructure/Pika.php'.

    $ ./bin/pomm.php pomm:generate:schema-all --psr4 --prefix-dir sources/lib/Model --prefix-ns PommProject\ModelManager\Model pomm_test
     ✓  Creating file 'sources/lib/Model/PommTest/PommTestSchema/AutoStructure/Pika.php'.

**Comment by chanmix51** [comment]
:+1:

**Comment by alanpearce** [comment]
`--psr4` sounds good to me as well. I don't think I'll be able to work on this for a while unfortunately, as I'm moving countries.

**Comment by stood** [comment]
:+1:  :+1:  :)

**Comment by tlode** [comment]
:+1: 
would you also consider adding an option to surpress the `Schema` suffix?

**Comment by chanmix51** [comment]
The `--ns-format` option should do this job.

**Comment by tlode** [comment]
ah, right :+1: thanks

**Comment by stood** [comment]
https://github.com/pomm-project/Cli/pull/13

**Comment by chanmix51** [comment]
Done with @stood's PR.
