### ISSUE TITLE
"Dangerous" namespace reference in generated class

### ISSUE THREAD

**Issue by xenji** [pomm-project/Cli#19]
The generated model has a reference to the flexible entity class [1]. This class name is quoted with double quotes, which makes the backslash-something characters interpretable. This might lead to defects in referencing classes whenever an escaped character with a special meaning occurs. 

Most prominent examples are \n and \t.

[1] https://github.com/pomm-project/Cli/blob/master/sources/lib/Generator/ModelGenerator.php#L129

**Comment by xenji** [comment]
Hopefully I get the time for a little pull request today, but please don't rely on that.

**Comment by chanmix51** [comment]
Good catch !

**Comment by chanmix51** [comment]
Done in e6a2451
