### ISSUE TITLE
Absolute Path with option --prefix-dir

### ISSUE THREAD

**Issue by Pierozi** [pomm-project/Cli#20]
Hello,
I discover a light bug with prefix option, the first slash are remove by `ltrim`.
I don't know why `ltrim` is there, that should be `rtrim` no ? for avoid double slash at right if path end with slash.

```php
# https://github.com/pomm-project/Cli/blob/master/sources/lib/Command/SchemaAwareCommand.php#L138
$elements =
  [
    ltrim($this->prefix_dir, '/'),
    $prefix_ns,
    Inflector::studlyCaps($config_name),
    Inflector::studlyCaps(sprintf("%s_schema", $this->schema)),
    $extra_dir,
    sprintf("%s%s.php", Inflector::studlyCaps($file_name), $file_suffix)
  ];
```

```bash
$ php /app/vendor/bin/pomm.php pomm:generate:schema-all -b /app/.pomm_cli_bootstrap.php \ 
 --prefix-dir /app/src//// \
 --prefix-ns "\Plab\Iced\Core" \
 --psr4

# with ltrim
app/src/////Model/CatalogSchema/AutoStructure/Attribute.php

# with rtrim
/app/src/Model/CatalogSchema/AutoStructure/Attribute.php

# when ltrim removed
/app/src/////Model/CatalogSchema/AutoStructure/Attribute.php

**Comment by stood** [comment]
No, it's the responsibility of user.

But if you delete ltrim and you use --prefix-dir /app, you will  have a problem. In fact with linux '/' is a root directory and your files will be generate in this directory.

**Comment by Pierozi** [comment]
Like you said, "responsibility of user" let user make choice.
My example is run under Docker container.

But I don't understand your point of  `"will have a problem"` problem is to define absolute path.
There are same problem if we put `/var/www/website/....`

**Comment by stood** [comment]
Ok i see but for me if you delete ltrim, many people will do the fault when add '/' at  first but why not add the option '--absolute-dir'

**Comment by Pierozi** [comment]
You right, BC-Break would be bad.
even if add `'/'` at first is the real error from user.

Option `--absolute-dir` seems good choice :+1:

**Comment by Pierozi** [comment]
btw, add `rtrim` should be also good for have a clean path.

**Comment by sanpii** [comment]
> Ok i see but for me if you delete ltrim, many people will do the fault when add '/' at first but why not add the option '--absolute-dir'

If a user makes a mistake, he makes a mistake… `mv` doesn’t have `--absolute-dir` option.

I think `ltrim` is a typo, replacing by `rtrim` seems a good idea.

**Comment by stood** [comment]
ok but ```mv``` doesn't have correct syntax option

If we accept who a user makes a mistake we have to remove ltrim and rtrim

I think ```ltrim``` is just an angel which save time for debug  :)

**Comment by chanmix51** [comment]
I do agree with Sanpi, we shall not try to think in place of the user, this means trying to be intelligent which most of the time end up with being … well :) at least awkward. 

Keep It Simple & Stupid
