### ISSUE TITLE
Misleading Session object passed to BaseGenerator

### ISSUE THREAD

**Issue by ronanguilloux** [pomm-project/Cli#25]
=> PommProject\Cli\Test\Unit\Command\GenerateEntity::testExecute():
==> Error CATCHABLE FATAL ERROR in /home/travis/build/pomm-project/Cli/sources/tests/Unit/Command/GenerateEntity.php on unknown line, generated by file /home/travis/build/pomm-project/Cli/vendor/pomm-project/model-manager/sources/lib/Generator/BaseGenerator.php on line 54:
Argument 1 passed to PommProject\ModelManager\Generator\BaseGenerator::__construct() must be an instance of PommProject\ModelManager\Session, instance of PommProject\Foundation\Session given, called in /home/travis/build/pomm-project/Cli/sources/lib/Command/GenerateEntity.php on line 85 and defined

See https://travis-ci.org/pomm-project/Cli/jobs/64483005

**Comment by chanmix51** [comment]
See [this commit](https://github.com/pomm-project/Cli/commit/686dddc56853ca2e8cf97c67fd3b54e3411c2108).

**Comment by stood** [comment]
Closed or not?
