### ISSUE TITLE
Test suite is not runnable on Windows OS

### ISSUE THREAD

**Issue by v3106** [pomm-project/Cli#29]
Usage of platform-specific features like `rm` and `\n` makes almost all tests unusable on Windows OS. I can provide a patch, if there is a need, but I need to know first what way is preferred for implementing an `rm -r` analogue: using something like Symfony's [Filesystem::remove()](https://github.com/symfony/Filesystem/blob/master/Filesystem.php#L152) by requiring it in the composer's `require-dev` section, or using standalone helper function.

**Comment by chanmix51** [comment]
:+1: for using a dedicated library.

**Comment by v3106** [comment]
Fixed in https://github.com/pomm-project/Cli/commit/22fb3731a2a6ddb277c064118696eb63c3ed52f0

**Comment by chanmix51** [comment]
Thank you for your support.
