### ISSUE TITLE
 Default directory structure without 'Mydb\PublicSchema'

### ISSUE THREAD

**Issue by shamotj** [pomm-project/Cli#31]
I originally created this in wrong project pomm-bundle https://github.com/pomm-project/pomm-bundle/issues/42. 

Pomm generates model, structure and other files to directory structure Connectionalias\Schema. If I have only one connection to DB, which I believe is very common scenario, I think that there could be something like "default connction" which will ommit this in namespace and in path. In result there will be only src/AppBundle/Model/ instead of src/AppBundle/Model/Mydb/PublicSchema/.

**Comment by webaaz** [comment]
I'm not fan. It's not a good idea if you want add another database later... 
I think we can add an option to do that instead of a default case.

**Comment by shamotj** [comment]
I agree it should not be default behavior. If it will be available through option it will be sufficient.

**Comment by chanmix51** [comment]
I think the better idea is to let naming to the developer using a parameter like`--dir-structure="%conalias%/%schema%"` like it is in Pomm 1.x

Pomm 2 is in Release Candidate process now so we do not add new features. This will be added in the 2.1 version.

**Comment by ishenkoyv** [comment]
+1 vote from me

**Comment by webaaz** [comment]
In symfony 3.4 with Flex, /src is mapped with the namespace App. So I need to move my entities after generation.
It's should be cool if we can decorrelate base path and base namespace.

**Comment by chanmix51** [comment]
@webaaz have you tried the `--psr4` option?

**Comment by webaaz** [comment]
It's ok with `--psr4` option.
It works withy a command like `./bin/console pomm:generate:relation-all -d 'src/Model/Pomm' -a 'App\Model\Pomm' mydb mytable --psr4`

**Comment by chanmix51** [comment]
Fixed with 387f32b2143196602f498ab370890927878a53f2
