### ISSUE TITLE
[Question] what about migrations?

### ISSUE THREAD

**Issue by dvc** [pomm-project/Cli#48]
Hello everibody!

Awesome project! Looks very cool!

One question: how can i mirgate my schema and some data with versioning? 

Is where something like doctrine-migrations for Pomm?

**Comment by rdavaillaud** [comment]
Hi,
My teams use [Phinx](https://phinx.org/) to handle migration.
We don't use the "table as object" part, just plain SQL queries. Without any real argument though ;-)

**Comment by dvc** [comment]
I see. Thank you!
